CREATE TABLE TB_STATUS(
	ID			UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	DS_STATUS	VARCHAR(100) NOT NULL,
	DT_CREATED	DATETIME,
	DT_UPDATED	DATETIME,
	ST_ACTIVE	BIT	DEFAULT 1
);

CREATE TABLE TB_GENDER(
	ID			UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	DS_GENDER	VARCHAR(100) NOT NULL,
	DT_CREATED	DATETIME,
	DT_UPDATED	DATETIME,
	ST_ACTIVE	BIT	DEFAULT 1
);

CREATE TABLE TB_MEDIA_TYPE(
	ID				UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	DS_MEDIA_TYPE	VARCHAR(100) NOT NULL,
	DS_EXTENSIONS	VARCHAR(100) NOT NULL,
	DT_CREATED		DATETIME,
	DT_UPDATED		DATETIME,
	ST_ACTIVE		BIT	DEFAULT 1
);

CREATE TABLE TB_USER(
	ID			UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	NM_USER		VARCHAR(100) NOT NULL,
	DS_EMAIL	VARCHAR(250) NOT NULL,
	DS_PASSWORD	VARCHAR(100) NOT NULL,
	DT_BIRTHDAY	DATE,
	ID_GENDER	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_GENDER(ID) NOT NULL,	
	DT_CREATED	DATETIME,
	DT_UPDATED	DATETIME,
	ST_ACTIVE	BIT	DEFAULT 1
);

CREATE TABLE TB_INVITE(
	ID			UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	ID_SENDER	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_USER(ID) NOT NULL,
	ID_RECEIVER	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_USER(ID) NOT NULL,
	DT_CREATED	DATETIME,
	DT_UPDATED	DATETIME,
	ID_STATUS	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_STATUS(ID) NOT NULL
);

CREATE TABLE TB_POST(
	ID			UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	ID_PARENT   UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_POST(ID),
	ID_AUTHOR	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_USER(ID) NOT NULL,
	DS_TEXT		VARCHAR(4000) NOT NULL,
	DT_CREATED	DATETIME,
	DT_UPDATED	DATETIME,
	ST_ACTIVE	BIT	DEFAULT 1
);

CREATE TABLE TB_GALLERY(
	ID			UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	ID_AUTHOR	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_USER(ID) NOT NULL,
	NM_GALLERY	VARCHAR(200) NOT NULL,
	DS_GALLERY	VARCHAR(4000),
	DT_CREATED	DATETIME,
	DT_UPDATED	DATETIME,
	ST_ACTIVE	BIT	DEFAULT 1
);
CREATE TABLE TB_MEDIA(
	ID				UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	ID_AUTHOR		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_USER(ID) NOT NULL,
	ID_POST			UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_POST(ID) NOT NULL,
	ID_MEDIA_TYPE	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_MEDIA_TYPE(ID) NOT NULL,
	ID_GALLERY		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_GALLERY(ID),
	DS_MEDIA		VARCHAR(4000),
	DS_PATH			VARCHAR(200) NOT NULL,
	DT_CREATED		DATETIME,
	DT_UPDATED		DATETIME,
	ST_ACTIVE	BIT	DEFAULT 1
);

ALTER TABLE TB_USER ADD ID_PROFILE	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_MEDIA(ID) NOT NULL;
ALTER TABLE TB_USER ADD ID_COVER	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_MEDIA(ID) NOT NULL;

CREATE TABLE TB_LIKE(
	ID_LIKE		UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	ID_POST		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_POST(ID),
	ID_MEDIA	UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_MEDIA(ID),
	ID_USER		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TB_USER(ID) NOT NULL, --USUARIO QUE CURTIU
	DT_CREATED	DATETIME,
	DT_UPDATED	DATETIME,
	ST_ACTIVE	BIT	DEFAULT 1
);

------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------


SELECT * FROM TB_STATUS A;

INSERT INTO TB_STATUS(ID,DS_STATUS,DT_CREATED,ST_ACTIVE) VALUES(1,'AGUARDANDO','20200204 01:00:00', 1);
INSERT INTO TB_STATUS(ID,DS_STATUS,DT_CREATED,ST_ACTIVE) VALUES(2,'ADICIONADO','20200204 01:00:00', 1);
INSERT INTO TB_STATUS(ID,DS_STATUS,DT_CREATED,ST_ACTIVE) VALUES(3,'RECUSADO'  ,'20200204 01:00:00', 1);
INSERT INTO TB_STATUS(ID,DS_STATUS,DT_CREATED,ST_ACTIVE) VALUES(4,'BLOQUEADO' ,'20200204 01:00:00', 1);

------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM TB_GENDER A;

INSERT INTO TB_GENDER(ID,DS_GENDER,DT_CREATED,ST_ACTIVE) VALUES(1,'FEMININO','20200204 01:00:00', 1);
INSERT INTO TB_GENDER(ID,DS_GENDER,DT_CREATED,ST_ACTIVE) VALUES(2,'MASCULINO','20200204 01:00:00', 1);
INSERT INTO TB_GENDER(ID,DS_GENDER,DT_CREATED,ST_ACTIVE) VALUES(3,'OUTROS','20200204 01:00:00', 1);

------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM TB_MEDIA A;

INSERT INTO TB_MEDIA(ID, DS_MEDIA, DT_CREATED, ST_ACTIVE) VALUES(1, 'FOTO','20200204 01:00:00', 1);
INSERT INTO TB_MEDIA(ID, DS_MEDIA, DT_CREATED, ST_ACTIVE) VALUES(2, 'VIDEO','20200204 01:00:00', 1);

------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM TB_USER A;

INSERT INTO TB_USER(ID, NM_USER, DS_EMAIL, DS_PASSWORD, DT_BIRTHDAY, ID_GENDER, DT_CREATED, ST_ACTIVE) 
VALUES(1,'SARA PINHEIRO MALDONADO CANTÃO', 'sarapmc@hotmail.com','1234','19920925', 1, '20200204 01:00:00', 1);
INSERT INTO TB_USER(ID, NM_USER, DS_EMAIL, DS_PASSWORD, DT_BIRTHDAY, ID_GENDER, DT_CREATED, ST_ACTIVE) 
VALUES(2,'VIVIAN', 'xpto@hotmail.com', '1234','19950109', 1, '20200204 01:00:00', 1);
INSERT INTO TB_USER(ID, NM_USER, DS_EMAIL, DS_PASSWORD, DT_BIRTHDAY, ID_GENDER, DT_CREATED, ST_ACTIVE) 
VALUES(3,'MARA', 'xpto@hotmail.com', '1234','19901020', 1, '20200204 01:00:00', 1);
INSERT INTO TB_USER(ID, NM_USER, DS_EMAIL, DS_PASSWORD, DT_BIRTHDAY, ID_GENDER, DT_CREATED, ST_ACTIVE) 
VALUES(4,'ANA', 'xpto@hotmail.com', '1234','19960606', 1, '20200204 01:00:00', 1);
INSERT INTO TB_USER(ID, NM_USER, DS_EMAIL, DS_PASSWORD, DT_BIRTHDAY, ID_GENDER, DT_CREATED, ST_ACTIVE) 
VALUES(5,'LINA', 'xpto@hotmail.com', '1234','19900227', 1, '20200204 01:00:00', 1);

------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM TB_INVITE A;

INSERT INTO TB_INVITE(ID, ID_SENDER, ID_RECEIVER, DT_CREATED, ID_STATUS) VALUES(1,1,2,'20200204 01:00:00', 1);
INSERT INTO TB_INVITE(ID, ID_SENDER, ID_RECEIVER, DT_CREATED, ID_STATUS) VALUES(2,1,3,'20200204 01:00:00', 1);
INSERT INTO TB_INVITE(ID, ID_SENDER, ID_RECEIVER, DT_CREATED, ID_STATUS) VALUES(3,1,4,'20200204 01:00:00', 1);
INSERT INTO TB_INVITE(ID, ID_SENDER, ID_RECEIVER, DT_CREATED, ID_STATUS) VALUES(4,1,5,'20200204 01:00:00', 1);

SELECT (A.ID_RECEIVER) AS ID, B.NM_USER 
FROM TB_INVITE A INNER JOIN TB_USER B ON B.ID = A.ID_RECEIVER 
WHERE A.ID_SENDER = 1 /*AND A.ID_STATUS = 8*/--STATUS "ADICIONADO"

UNION

SELECT (A.ID_SENDER) AS ID, B.NM_USER 
FROM TB_INVITE A INNER JOIN TB_USER B ON B.ID = A.ID_SENDER 
WHERE A.ID_RECEIVER = 1 /*AND A.ID_STATUS = 8*/;

------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM TB_POST A;

INSERT INTO TB_POST(ID, ID_AUTHOR, DS_TEXT, DT_CREATED, ST_ACTIVE) VALUES(1,1, 'MEU 1º POST ! ', '20200205 20:00:00', 1);
INSERT INTO TB_POST(ID, ID_AUTHOR, DS_TEXT, DT_CREATED, ST_ACTIVE) VALUES(2,1, 'MEU 2º POST ! ', '20200205 21:00:00', 1);

------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM TB_MEDIA A;

--"C:\Users\Avanade\Documents\REDESOCIAL\FOTO\" --ID_USUARIO\FOTO (VER SE UTILIZA POR DATA/HORA OU PELO ID DA FOTO)
INSERT INTO TB_MEDIA(ID, ID_POST, ID_AUTHOR, ID_MEDIA_TYPE, DS_MEDIA, DS_PATH, DT_CREATED, ST_ACTIVE)
VALUES(1,1,1,1, 'CAPTION!', '1\20200204_192700.BMP', 1, 0, '20200205 20:00:00', 1);

------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM TB_LIKE A;

INSERT INTO TB_LIKE(ID_LIKE, ID_POST, ID_MEDIA, ID_USER, DT_CREATED, ST_ACTIVE) VALUES(1,1,1,1,'20200205 20:00:00', 1);
